Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
empty_arr = np.empty((2,2))
one_arr = np.ones((4,2))
print(empty_arr)
print(one_arr)
full_arr = np.full((2,2), 7)
print(full_arr)
zeros_like_arr = np.zeros_like(one_arr)
print(zeros_like_arr)
ones_like_arr = np.ones_like(empty_arr)
print(ones_like_arr)
new_list = [1,2,3,4]
arr_list = np.array(new_list)
print(arr_list)

[[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

#Create an array with values ranging from 10 to 49.
arr_range = np.arange(10,50)
print("Matrix from 10-49: ",arr_range)

#Create a 3X3 matrix with values ranging from 0 to 8.
arr_3x3_range = np.arange(0,9).reshape((3,3))
print("3 x 3 matrix from 0-8: ", arr_3x3_range)

#Create a 3X3 identity matrix.
arr_3x3_identity = np.eye(3,3)
print("3 x 3 identity matrix: ",arr_3x3_identity)

#Create a random array of size 30 and find the mean of the array.
arr_random = np.random.random(30)
print("Random array of size 30: ", arr_random)

#Create a 10X10 array with random values and find the minimum and maximum values.
arr_rand_10x10 = np.random.rand(10, 10)
print("Random 10 x 10 matrix: ", arr_rand_10x10)
max = arr_rand_10x10.max()
min = arr_rand_10x10.min()
print("Max is:", max)
print("MIn is:", min)

#Create a zero array of size 10 and replace 5th element with 1.
arr_zero_10 = np.zeros(10)
arr_zero_10[4] = 1
print("Zero array of size 10 with 5th element as 1: ", arr_zero_10)

#Reverse an array arr = [1,2,0,0,4,0].
arr = [1,2,0,0,4,0]
arr_reversed = np.array(arr)[::-1]
print("Reversed array: ", arr_reversed)

#Create a 2d array with 1 on border and 0 inside.
arr_2d = np.zeros((2,2))
bordered_arr = np.pad(arr_2d, pad_width = 1, mode='constant', constant_values=1)
print("Bordered array: \n", bordered_arr)

# Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard_arr = np.indices((8, 8)).sum(axis=0) % 2
print("Checkerboard_arr: \n", checkerboard_arr)


Matrix from 10-49:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3 x 3 matrix from 0-8:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
3 x 3 identity matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array of size 30:  [0.92808545 0.21907613 0.9420212  0.99188155 0.97237093 0.64872702
 0.03227679 0.93778637 0.45403452 0.71670451 0.38384413 0.58310922
 0.16935394 0.47538836 0.9443112  0.33009105 0.84957356 0.16446214
 0.39863366 0.80951877 0.50077506 0.91715821 0.07421513 0.01134456
 0.40176484 0.14711471 0.71636362 0.51540484 0.58408583 0.10945759]
Random 10 x 10 matrix:  [[0.11387486 0.91500552 0.56338702 0.09841004 0.73625198 0.35825315
  0.4528579  0.40100647 0.17172946 0.70554997]
 [0.27496209 0.17974191 0.21910193 0.98872716 0.82522655 0.29784763
  0.50253066 0.44957968 0.99327804 0.77520103]
 [0.36945793 0.55246518 0.71678093 0.26061313 0.73542466 0.32909747
  0.09706366 0.7105003  0.67429553 0.79743351]
 [0.05908229 

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# Adding the two arrays
add_2x2 = np.add(x,y)
add_1x2 = np.add(v,w)
print("Addition of x and y: \n", add_2x2)
print("Addition of v and w: ", add_1x2)

# Subtracting the two arrays
sub_2x2 = np.add(x,-y)
sub_1x2 = np.subtract(v,w)
print("Substraction of x and y: \n", sub_2x2)
print("Substraction of v and w: ", sub_1x2)

# Multiplying the array with any integers of my choice
mul_num = 2
mul_arr_x = np.multiply(x,mul_num)
print(f"Multiplying x with {mul_num} : \n", mul_arr_x)

# Find the square of each element of the array.
sqr_arr_y = np.power(y, 2)
print("Square of array y is: \n", sqr_arr_y)

# Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_x_y = np.dot(x,y)
dot_v_w = np.dot(v,w)
dot_x_v = np.dot(x,v)
print("Dot product of x and y: \n", dot_x_y)
print("Dot product of v and w: \n", dot_v_w)
print("Dot product of x and v: \n", dot_x_v)

# Concatenate x(and)y along row and Concatenate v(and)w along column.
concat_x_y = np.concatenate((x,y),axis=0)
stack_x_y = np.vstack((x,y))

stack_v_w = np.hstack((v,w))
print("Concatination of x and y along row: \n", concat_x_y)
print("Stacking of x and y along row: \n", stack_x_y)
print("Stacking of v and w along row: \n", stack_v_w)

# Concatenate x(and)v
# concate_x_v = np.concatenate((x,v),axis=0)

Addition of x and y: 
 [[ 6  8]
 [10 13]]
Addition of v and w:  [20 22]
Substraction of x and y: 
 [[-4 -4]
 [-4 -3]]
Substraction of v and w:  [-2 -2]
Multiplying x with 2 : 
 [[ 2  4]
 [ 6 10]]
Square of array y is: 
 [[25 36]
 [49 64]]
Dot product of x and y: 
 [[19 22]
 [50 58]]
Dot product of v and w: 
 219
Dot product of x and v: 
 [29 77]
Concatination of x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Stacking of x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Stacking of v and w along row: 
 [ 9 10 11 12]


The code had a ValueError as the dimensions of both the array is not the same. The array x has the dimensions of 2x2 but array v has the dimensions of 1x2.

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT.

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Prove A.A−1 = I.
A_inverse = np.linalg.inv(A)

mul_A_Ainv = np.dot(A, A_inverse)
print("Multiplication of A and A_inverse: \n", mul_A_Ainv)
idenity_matrix = np.eye(A.shape[0])
print("Identity matrix: \n", idenity_matrix)

is_identity = np.allclose(mul_A_Ainv, idenity_matrix)
if(is_identity):
    print("The matrix multiplication of A and its inverse is an Identity matrix or close to it.")
    print("Hence Proved.")
else:
    print("Not Proved.")

# Prove AB ̸= BA.
mul_AB = np.matmul(A,B)
mul_BA = np.matmul(B,A)
print("Multiplication of A and B: \n", mul_AB)
print("Multiplication of B and A: \n", mul_BA)

equal_mul = np.array_equal(mul_AB, mul_BA)
if(not equal_mul):
    print("The matrix multiplication of A and B is not equal to the matrix multiplication of B and A.")
    print("Hence Proved.")
else:
    print("The matrix multiplication of A and B is equal to the matrix multiplication of b and A.")
    print("Not proved.")

# Prove (AB)T = BTAT
A_transpose = np.transpose(A)
B_transpose = np.transpose(B)
AB_transpose = np.transpose(mul_AB)
print("The Transpose of AB ((AB)T) is: \n", AB_transpose)
B_trans_A_trans = np.matmul(B_transpose, A_transpose)
print("The Transpose of B multiplied with Transpose of A (BTAT) is: \n", B_trans_A_trans)

equal_trans = np.array_equal(AB_transpose, B_trans_A_trans)
if(equal_trans):
    print("The transpose of AB and transpose of B multiplied with transpose of A is equal.")
    print("Hence Proved.")
else:
    print("Not Proved.")

Multiplication of A and A_inverse: 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix: 
 [[1. 0.]
 [0. 1.]]
The matrix multiplication of A and its inverse is an Identity matrix or close to it.
Hence Proved.
Multiplication of A and B: 
 [[23 13]
 [51 29]]
Multiplication of B and A: 
 [[36 44]
 [13 16]]
The matrix multiplication of A and B is not equal to the matrix multiplication of B and A.
Hence Proved.
The Transpose of AB ((AB)T) is: 
 [[23 51]
 [13 29]]
The Transpose of B multiplied with Transpose of A (BTAT) is: 
 [[23 51]
 [13 29]]
The transpose of AB and transpose of B multiplied with transpose of A is equal.
Hence Proved.


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

# representing in augmented matrix form

# Matrix of coefficients
a = [
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
    ]
A = np.array(a)

# Matrix of constants
b = [-1,-3,9]
B = np.array(b)

# Using inverse method
A_inverse = np.linalg.inv(A)
X = np.matmul(A_inverse, B)
print("The value of x, y, z is: \n", X)


The value of x, y, z is: 
 [ 2.  1. -2.]


Experiment: How Fast is Numpy?

1. Element-wise Addition
2. Element-wise Multiplication
3. Dot Product
4. Matrix Multiplication

In [ ]:
import numpy as np
import random
from timeit import timeit
# Creating two different lists of size 1000000
size = 1000000
A_list = random.sample(range(size + 1), size)
B_list = random.sample(range(size + 1), size)
A_array = np.array(A_list)
B_array = np.array(B_list)
result = []

# for python add
def python_add(A, B):
  for i in range(len(A)):
    result.append(A[i] + B[i])
  return result
python_time_add = timeit("python_add(A_list, B_list)", globals=globals(), number=100)
print("Python time for add: ", python_time_add)
# for numpy add
def numpy_add(A, B):
  return A + B
numpy_time_add = timeit("numpy_add(A_array, B_array)", globals=globals(), number=100)
print("Numpy time for add: ", numpy_time_add)

# for python multiplication
def python_mul(A, B):
  for i in range(len(A)):
    result.append(A[i] + B[i])
  return result
python_time_mul = timeit("python_mul(A_list, B_list)", globals=globals(), number=100)
print("Python time for multiplication: ", python_time_mul)

# for numpy multiplication
def numpy_mul(A, B):
  return np.multiply(A, B)
numpy_time_mul = timeit("numpy_mul(A_array, B_array)", globals=globals(), number=100)
print("Numpy time for multiplication: ", numpy_time_mul)

# for python dot product
def python_dot(A, B):
  result =  sum(a * b for a, b in zip(A, B))
  return result
python_time_dot = timeit("python_dot(A_list, B_list)", globals=globals(), number=100)
print("Python time for dot product: ", python_time_dot)

# for numpy dot
def numpy_dot(A, B):
  return np.dot(A, B)
numpy_time_dot = timeit("numpy_dot(A_array, B_array)", globals=globals(), number=100)
print("Numpy time for dot product: ", numpy_time_dot)

matrix_size =300 # Adjust as needed
Z1_matrix_list = [A_list[i:i + matrix_size] for i in range(0, matrix_size ** 2, matrix_size)]
Z2_matrix_list = [B_list[i:i + matrix_size] for i in range(0, matrix_size ** 2, matrix_size)]

Z1_matrix_arr = np.array(Z1_matrix_list)
Z2_matrix_arr = np.array(Z2_matrix_list)
# for python matrix multiplication
def python_matmul(A,B):
    return [
        [sum(a * b for a,b in zip(row_A, col_B)) for col_B in zip(*B)]
        for row_A in A
    ]

python_time_matmul = timeit("matrix_python(Z1_matrix_list, Z2_matrix_list)", globals=globals(), number=10)
print("Python time for dot product: ", python_time_matmul)

# for numpy matrix multiplication
def numpy_matmul(A, B):
  return np.matmul(A, B)
numpy_time_matmul = timeit("numpy_matmul(Z1_matrix_arr, Z2_matrix_arr)", globals=globals(), number=10)
print("Numpy time for matrix multiplication: ", numpy_time_matmul)

Python time for add:  43.57272779599998
Numpy time for add:  0.18940262000000985
Python time for multiplication:  44.00085040800002
Numpy time for multiplication:  0.1782109619999801
Python time for dot product:  34.76507288000005
Numpy time for dot product:  0.10804748300006395
Python time for dot product:  72.525050136
Numpy time for matrix multiplication:  0.28325286100005087
